### ISSUE TITLE
Updated wiki in fork

### ISSUE THREAD

**Issue by gooddadmike** [CodeLouisville/Student-Resources#1]
See PR and ref git repo for wiki

I moved all this stuff to Wiki, so students can add to it for the stuff we want to reference but slack erases. 

All you have to do is start a wiki page so a blank wiki repo exists. Clone wiki repo add my files and commit.

I even updated to reflect your commits from yesterday @beckysteele .

I understand if you want to keep as separate .md files but [browse my wiki](https://github.com/getthemike/Student-Resources/wiki) and decide for yourself. 

I think it will be easier for people to contribute to and feels more cohesive than just separate md files floating around. 

Plus it would be my first accepted PR outside my job!

clone wiki: https://github.com/getthemike/Student-Resources.wiki.git
view it here: https://github.com/getthemike/Student-Resources/wiki

**Comment by beckysteele** [comment]
Okay Mike!  I had a little problem with the merge on my end, but the PR is closed now and we have the Wiki!  I really appreciate your help on this!  Personally, I also appreciate the extra practice with merging files :octocat:

**Comment by gooddadmike** [comment]
I had never done that with a wiki before either. I'm glad you like it as a
wiki. I think it's a good change. Thanks for the PR.
